apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: letsencrypt
  namespace: openshift-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: letsencrypt
subjects:
- kind: ServiceAccount
  name: letsencrypt
  namespace: letsencrypt